/* Central sample content. Replace with verified, approved business information. */
window.CREOVO = {
  brand: 'CreovoCafe', template: true,
  products: [
    {id:'classic-churros',name:'The classic churros',ar:'التشوروز الكلاسيكي',category:'churros',description:'Golden, cinnamon-dusted, made for dipping.',descriptionAr:'تشوروز ذهبي بالقرفة، مثالي مع صلصة الشوكولاتة.',detail:'A little crunch, a soft center, and a generous dusting of cinnamon sugar. Pair this sample selection with your favorite coffee.',image:'churros-800.webp',alt:'Cinnamon churros with a chocolate dipping sauce',tag:'THE SIGNATURE',allergens:'Recipe and allergens awaiting confirmation.'},
    {id:'house-latte',name:'Your everyday latte',ar:'لاتيه لكل يوم',category:'coffee',description:'A smooth little pick-me-up. Your way.',descriptionAr:'قهوتك الناعمة للحظاتك اليومية.',detail:'A comforting espresso and milk pairing. The final recipe, milk options, serving sizes, and availability will be added to the live menu.',image:'coffee-detail.webp',alt:'A ceramic cappuccino cup with latte art',tag:'THE DAILY RITUAL',allergens:'Recipe and allergens awaiting confirmation.'},
    {id:'coffee-pastry',name:'The perfect little pair',ar:'الثنائي المثالي',category:'coffee',description:'Something to sip. Something to savor.',descriptionAr:'رشفة قهوة ولقمة حلوة، معاً دائماً.',detail:'A coffee and pastry pairing for an unhurried moment. This is an illustrative menu concept; final combinations will be confirmed before launch.',image:'coffee-pastry-900.webp',alt:'Coffee and an almond croissant together on a wooden table',tag:'BETTER TOGETHER',allergens:'Recipe and allergens awaiting confirmation.'},
    {id:'chocolate-churros',name:'Chocolate-dipped joy',ar:'فرحة بالشوكولاتة',category:'churros',description:'A golden bite meets a darker kind of sweet.',descriptionAr:'تشوروز ذهبي مع الشوكولاتة الغنية.',detail:'An indulgent variation of the signature churros concept, with chocolate for dipping. Photograph is illustrative.',image:'churros-800.webp',alt:'Churros beside a cup of rich chocolate sauce',tag:'SWEET LITTLE THINGS',allergens:'Recipe and allergens awaiting confirmation.'},
    {id:'cold-coffee',name:'A cooler coffee moment',ar:'لحظة قهوة باردة',category:'cold',description:'Your coffee ritual, with a little chill.',descriptionAr:'طقوس القهوة بنكهة منعشة.',detail:'A chilled coffee concept for the sample menu. Final recipe and product photography are to be supplied. The image shows our illustrative café setting.',image:'cafe-interior-1600.webp',alt:'An illustrative café setting for the chilled drinks concept',tag:'CHILLED COFFEE CONCEPT',allergens:'Recipe and allergens awaiting confirmation.'}
  ],
  branches: [
    {id:'neighborhood',name:'The neighborhood café',ar:'مقهى الحي',subtitle:'A familiar little corner.',intro:'Imagine a place woven into your everyday: the table by the window, your favorite cup, and a reason to linger.',image:'cafe-interior-1600.webp',number:'01'},
    {id:'city',name:'The city retreat',ar:'استراحة المدينة',subtitle:'A pause in the middle of it all.',intro:'A café concept for the moments between meetings and the conversations that make a busy day feel lighter.',image:'cafe-interior-1600.webp',number:'02'},
    {id:'gathering',name:'The gathering place',ar:'مكان اللقاء',subtitle:'A little more room for your people.',intro:'Long conversations, shared plates, and an extra chair at the table. A concept designed around being together.',image:'coffee-pastry-900.webp',number:'03'},
    {id:'quiet',name:'The quiet corner',ar:'الركن الهادئ',subtitle:'Make a little time for yourself.',intro:'A space imagined for unhurried mornings, a favorite book, and a cup you can take your time with.',image:'barista-900.webp',number:'04'}
  ]
};
