/* Production metadata is opt-in. Do not enable until template copy is replaced. */
const fs=require('node:fs'),vm=require('node:vm');
const config=JSON.parse(fs.readFileSync('site.config.json','utf8').replace(/^\uFEFF/,''));
const paths=['/','/menu/','/locations/','/about/','/catering/','/contact/','/reservations/','/offers/','/stories/','/privacy/','/locations/neighborhood/','/locations/city/','/locations/gathering/','/locations/quiet/'];
if(!config.production||!config.verifiedContent||!config.origin){console.log('Template stays noindex. Production canonical URLs, sitemap and entity graph require approved content and domain.');process.exit(0);}
const origin=new URL(config.origin).origin;if(!origin.startsWith('https://'))throw Error('Use your verified HTTPS origin');
const context={window:{}};vm.runInNewContext(fs.readFileSync('content.js','utf8'),context);const content=context.window.CREOVO;
const brand={'@type':'Organization','@id':origin+'/#brand',name:config.brandName,url:origin+'/'};
if(config.legalName)brand.legalName=config.legalName;if(config.socialAccounts.length)brand.sameAs=config.socialAccounts;
const website={'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:config.brandName,publisher:{'@id':brand['@id']},inLanguage:['en','ar']};
function branchEntity(b){
 if(!b.verified||!b.name||!b.address?.streetAddress||!b.address?.addressLocality||!b.address?.addressCountry) return null;
 const entity={'@type':'CafeOrCoffeeShop','@id':origin+'/locations/'+b.id+'/#cafe',name:b.name,url:origin+'/locations/'+b.id+'/',parentOrganization:{'@id':brand['@id']},address:{'@type':'PostalAddress',...b.address},hasMenu:{'@id':origin+'/menu/#menu'}};
 for(const field of ['telephone','image','openingHoursSpecification','priceRange','acceptsReservations','servesCuisine'])if(b[field]!==undefined&&b[field]!==null)entity[field]=b[field];
 if(Number.isFinite(b.latitude)&&Number.isFinite(b.longitude))entity.geo={'@type':'GeoCoordinates',latitude:b.latitude,longitude:b.longitude};
 return entity;
}
const menu={'@type':'Menu','@id':origin+'/menu/#menu',name:'CreovoCafe menu',hasMenuSection:['churros','coffee','cold'].map(category=>({'@type':'MenuSection','@id':origin+'/menu/#'+category,name:category,hasMenuItem:content.products.filter(p=>p.category===category).map(p=>({'@type':'MenuItem','@id':origin+'/menu/#'+p.id,name:p.name,description:p.description}))}))};
for(const lang of ['en','ar'])for(const route of paths){const localized=(lang==='ar'?'/ar':'')+route,file='.'+localized+'index.html';if(!fs.existsSync(file))continue;const url=origin+localized;let html=fs.readFileSync(file,'utf8');const branch=config.branches.find(b=>route==='/locations/'+b.id+'/');const entity=branch&&branchEntity(branch);const page={'@type':'WebPage','@id':url+'#page',url,name:html.match(/<title>(.*?)<\/title>/)?.[1],isPartOf:{'@id':website['@id']},inLanguage:lang};const graph=[brand,website,page];if(route==='/menu/')graph.push(menu);if(entity)graph.push(entity);const segments=route.split('/').filter(Boolean);graph.push({'@type':'BreadcrumbList','@id':url+'#breadcrumbs',itemListElement:[{'@type':'ListItem',position:1,name:lang==='ar'?'الرئيسية':'Home',item:origin+(lang==='ar'?'/ar/':'/')},...segments.map((segment,i)=>({'@type':'ListItem',position:i+2,name:segment,item:origin+(lang==='ar'?'/ar':'')+'/'+segments.slice(0,i+1).join('/')+'/'}))]});html=html.replace('<meta name="robots" content="noindex,nofollow">','<meta name="robots" content="index,follow">');html=html.replace('</head>',`<link rel="canonical" href="${url}"><link rel="alternate" hreflang="en" href="${origin+route}"><link rel="alternate" hreflang="ar" href="${origin+'/ar'+route}"><link rel="alternate" hreflang="x-default" href="${origin+route}"><meta property="og:url" content="${url}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c')}</script></head>`);fs.writeFileSync(file,html);}
fs.writeFileSync('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+['en','ar'].flatMap(lang=>paths.map(route=>'<url><loc>'+origin+(lang==='ar'?'/ar':'')+route+'</loc></url>')).join('')+'</urlset>');fs.writeFileSync('robots.txt','User-agent: *\nAllow: /\nDisallow: /admin/\nSitemap: '+origin+'/sitemap.xml\n');console.log('Generated production SEO metadata. Validate with the launch checklist.');
