'use strict';
const $=s=>document.querySelector(s);let data=structuredClone(window.CREOVO);const key='creovo-content-draft';
function valid(value){return value&&Array.isArray(value.products)&&Array.isArray(value.branches)&&['products','branches'].every(k=>value[k].length>0&&value[k].every(x=>x&&typeof x.id==='string'&&typeof x.name==='string'));}
try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved))data=saved;}catch{}
const fieldMap={products:{name:'Product name (English)',ar:'Product name (Arabic)',description:'Short description',descriptionAr:'Arabic description',detail:'Product story',allergens:'Allergen verification note'},branches:{name:'Branch concept name',ar:'Branch name (Arabic)',subtitle:'Short introduction',intro:'Branch story'}};
function entry(){return data[$('#collection').value].find(x=>x.id===$('#entry').value);}
function fields(){const item=entry();$('#fields').replaceChildren();for(const [name,label] of Object.entries(fieldMap[$('#collection').value])){const l=document.createElement('label');l.textContent=label;const input=document.createElement(name==='intro'||name==='detail'?'textarea':'input');input.name=name;input.value=item[name]||'';input.maxLength=2000;input.required=name==='name';l.append(input);$('#fields').append(l);}}
function options(){const list=data[$('#collection').value];$('#entry').replaceChildren(...list.map(x=>new Option(x.name,x.id)));fields();}
function capture(){if(!$('#editor').reportValidity())return false;for(const input of $('#fields').querySelectorAll('input,textarea'))entry()[input.name]=input.value;return true;}
$('#collection').addEventListener('change',options);$('#entry').addEventListener('change',fields);
$('#editor').addEventListener('submit',e=>{e.preventDefault();if(!capture())return;try{localStorage.setItem(key,JSON.stringify(data));$('#editor-status').textContent='Draft saved on this device. The public website has not changed.';}catch{$('#editor-status').textContent='Browser storage is unavailable. Use Export to keep your draft.'}});
$('#export').addEventListener('click',()=>{if(!capture())return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='creovo-content-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#editor-status').textContent='Draft exported. Your file is ready for the publishing workflow.';});
$('#import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1000000)throw Error('File too large');const value=JSON.parse(await file.text());if(!valid(value))throw Error('Invalid content structure');data=value;options();$('#editor-status').textContent='Draft imported. Save on this device to keep it.';}catch{$('#editor-status').textContent='Import failed. Choose a valid CreovoCafe draft JSON file under 1 MB.'}finally{e.target.value='';}});
$('#clear').addEventListener('click',()=>{localStorage.removeItem(key);data=structuredClone(window.CREOVO);options();$('#editor-status').textContent='Local draft cleared. Original template content restored in the editor.';});options();
